repos:
  
# populates the known_third_party of isort setting (thinks library is thirs party)
#  - repo: https://github.com/asottile/seed-isort-config 
#    rev: v2.1.1
#    hooks:
#    - id: seed-isort-config

# sorts all your imports!
 - repo: https://github.com/pre-commit/mirrors-isort
   rev: v4.3.21
   hooks:
   - id: isort

# The Uncompromising Code Formatter
 - repo: https://github.com/psf/black
   rev: 19.10b0
   hooks:
   - id: black
     language_version: python3.8

# Linter w/ plugins
 - repo: https://gitlab.com/pycqa/flake8
   rev: 3.8.2
   hooks:
   - id: flake8
     exclude: |
         (?x)(
             legacy/|
             migrations/
         )     
     additional_dependencies: [
     'flake8-import-order',
     'flake8-blind-except',
     'flake8-builtins',
     'flake8-docstrings',
     'flake8-bugbear',
     'flake8-comprehensions',
     'flake8-pep3101',
     # 'flake8-print'
     ]