# Generated by Django 3.0.7 on 2020-06-06 21:10

# django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="multiplechoicequiz", name="key", field=models.IntegerField(),
        ),
    ]
