# Generated by Django 3.0.6 on 2020-05-28 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200527_1738'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
